### ISSUE TITLE
Add support for SOCKS proxies

### ISSUE THREAD

**Issue by RevanProdigalKnight** [sublimelsp/LSP-jdtls#42]
I'm working in a place where in order for certain things to run properly on my system I have set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables to point to a proxy, but the LSP-jdtls extension fails to start with the following message:

![image](https://github.com/sublimelsp/LSP-jdtls/assets/5728037/c2e123c6-1fd8-43a4-bdbc-77b3cd1a0c92)

The stack trace in the console:

```txt
Unable to start subprocess for jdtls
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 245, in start_async
    plugin_class.install_or_update()
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP-jdtls.sublime-package\modules/jdtls.py", line 66, in install_or_update
    installer.install_or_update()
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP-jdtls.sublime-package\modules/installer.py", line 137, in install_or_update
    extract_tar(JDTLS_URL.format(version=version), jdtls_path())
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP-jdtls.sublime-package\modules/installer.py", line 69, in extract_tar
    _extract_file(url, path, lambda x: tarfile.open(x, "r:gz"))
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP-jdtls.sublime-package\modules/installer.py", line 48, in _extract_file
    download_file(url, compressed_file)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LSP-jdtls.sublime-package\modules/installer.py", line 35, in download_file
    with urlopen(url) as response, open(file_name, "wb") as out_file:
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 785, in <lambda>
  File "./python3.3/urllib/request.py", line 813, in proxy_open
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 492, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1316, in unknown_open
urllib.error.URLError: <urlopen error unknown url type: socks5>
```

I have attempted to circumvent the issue by using [ProjectEnvironment](https://packagecontrol.io/packages/ProjectEnvironment), but it does not appear to work correctly with other plugins.

**Comment by LDAP** [comment]
You can right-click the console input to switch to 3.3 mode

**Comment by RevanProdigalKnight** [comment]
Thanks, now I'm getting `ImportError: No module named 'socks'`. I'm guessing at this point that I need to find some other way around the problem.

**Comment by LDAP** [comment]
I guess you would have to vendor pysocks for this to work. At this point, I don't think it can or at least should be fixed within LSP-jdtls.

**Comment by RevanProdigalKnight** [comment]
Alright. Thanks for your help.

**Comment by hallboav** [comment]
Socks proxy needed.
